version: '3.4'

services:
  influxdb:
    image: influxdb:2.3-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-scripts:/docker-entrypoint-initdb.d
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
    healthcheck:
      test: wget --spider -q http://localhost:8086/ping || exit 1
      interval: 6s
      retries: 5
      start_period: 10s
      timeout: 10s
  telegraf:
    image: telegraf:1.23-alpine
    restart: unless-stopped
    user: telegraf:${DOCKER_GID}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      INFLUX_TOKEN: ${TELEGRAF_INFLUXDB_TOKEN}
      INFLUX_HOST: "http://influxdb:8086"
      INFLUX_ORG: ${INFLUXDB_INIT_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_INIT_BUCKET}
    depends_on:
      influxdb:
        condition: service_healthy

volumes:
  influxdb-data:
  influxdb-config:
